version: '2'
services:
  openresty:
    image: shawoo/openresty
    restart: always
    ports:
      - "8088:80"
    environment:
      ver: 0.1
    working_dir: /usr/local/openresty/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/local/openresty/nginx/html
      - ./lua:/usr/local/openresty/nginx/lua
